- name: Elimina Agente OneAgent
  hosts: all
  tasks:
    - name: Stop OneAgent
      ansible.builtin.service:
        name: oneagent
        state: stopped
    - name: Uninstall OneAgent
      become: yes
      shell: /opt/dynatrace/oneagent/agent/uninstall.sh > /tmp/Uninstall_OneAgent.out
    - name: Elimina Directorios
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /Dynatrace
        - /var/lib/dynatrace
        - /var/log/dynatrace
        - /opt/dynatrace
