- name: Hello World Sample
  hosts: all
  tasks:
    - name: Download OneAgent
      become: yes
      get_url:
        url: http://io.zuard.net:32769/api/public/dl/cGPW9kjn
        dest: /tmp/OneAgent.sh
        mode: 0755
    - name: Crear Directorios para Agente
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0775
      loop:
        - /Dynatrace/var/log/dynatrace
        - /Dynatrace/opt/dynatrace
        - /Dynatrace/var/lib/dynatrace
    - name: Crea enlaces symbolicos
      become: yes
      ansible.builtin.file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
      loop:
        - { src: /Dynatrace/var/log/dynatrace, dest: /var/log/dynatrace }
        - { src: /Dynatrace/opt/dynatrace, dest: /opt/dynatrace  }
        - { src: /Dynatrace/var/lib/dynatrace, dest: /var/lib/dynatrace  }
    - name: Instala OneAgent
      become: yes
      ansible.builtin.script: 
        cmd: /tmp/OneAgent.sh
