- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Download OneAgent
      become: yes
      get_url:
        url: http://io.zuard.net:32769/api/public/dl/A8VBAFx8
        dest: /tmp
        mode: 0755
