- name: Hello World Sample
  hosts: all
  tasks:
    - name: Download OneAgent
      become: yes
      get_url:
        url: http://io.zuard.net:32769/share/cGPW9kjn
        dest: /tmp/OneAgent.sh
        mode: 0755
    - name: Crear Directorios para Agente
      ansible.builtin.file:
      path: "{{item}}"
      with_items:
        - ["/Dynatrace/var/log/dynatrace","/Dynatrace/opt/dynatrace","/Dynatrace/var/lib/dynatrace"]
      state: directory
      mode: '0755'
