- name: Hello World Sample
  hosts: all
  tasks:
    - name: Download OneAgent
      become: yes
      get_url:
        url: http://io.zuard.net:32769/share/cGPW9kjn
        dest: /tmp/OneAgent.sh
        mode: 0755
    - name: Crear Directorios para Agente
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0775
      loop:
        - /Dynatrace/var/log/dynatrace
        - /Dynatrace/opt/dynatrace
        - /Dynatrace/var/lib/dynatrace
